global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'Links tracker'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8081', 'host.docker.internal:8091']
