app:
  scheduler:
    enable: true
    invoke-interval: 10s
    force-check-delay: 10s
    checkInterval: 600s

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: false


server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

github:
  base:
    url: "https://api.github.com"

stackOverflow:
  base:
    url: "https://api.stackexchange.com/2.3"

bot:
  base:
    url: http://localhost:8090
