app:
  telegram-token: 6986184535:AAENkty0j1ZiWLiD2X2itsjcKHanQ7SnxpU

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
