/*
 * This file is generated by jOOQ.
 */

package edu.java.repository.jooq.tables.records;

import edu.java.repository.jooq.tables.GithubLinks;
import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GithubLinksRecord extends UpdatableRecordImpl<GithubLinksRecord> implements Record2<Long, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GITHUB_LINKS.LINK_ID</code>.
     */
    public void setLinkId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>GITHUB_LINKS.LINK_ID</code>.
     */
    @Nullable
    public Long getLinkId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>GITHUB_LINKS.PULL_REQUESTS_COUNT</code>.
     */
    public void setPullRequestsCount(@Nullable Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>GITHUB_LINKS.PULL_REQUESTS_COUNT</code>.
     */
    @Nullable
    public Integer getPullRequestsCount() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Long, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return GithubLinks.GITHUB_LINKS.LINK_ID;
    }

    @Override
    @NotNull
    public Field<Integer> field2() {
        return GithubLinks.GITHUB_LINKS.PULL_REQUESTS_COUNT;
    }

    @Override
    @Nullable
    public Long component1() {
        return getLinkId();
    }

    @Override
    @Nullable
    public Integer component2() {
        return getPullRequestsCount();
    }

    @Override
    @Nullable
    public Long value1() {
        return getLinkId();
    }

    @Override
    @Nullable
    public Integer value2() {
        return getPullRequestsCount();
    }

    @Override
    @NotNull
    public GithubLinksRecord value1(@Nullable Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public GithubLinksRecord value2(@Nullable Integer value) {
        setPullRequestsCount(value);
        return this;
    }

    @Override
    @NotNull
    public GithubLinksRecord values(@Nullable Long value1, @Nullable Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GithubLinksRecord
     */
    public GithubLinksRecord() {
        super(GithubLinks.GITHUB_LINKS);
    }

    /**
     * Create a detached, initialised GithubLinksRecord
     */
    @ConstructorProperties({ "linkId", "pullRequestsCount" })
    public GithubLinksRecord(@Nullable Long linkId, @Nullable Integer pullRequestsCount) {
        super(GithubLinks.GITHUB_LINKS);

        setLinkId(linkId);
        setPullRequestsCount(pullRequestsCount);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised GithubLinksRecord
     */
    public GithubLinksRecord(edu.java.repository.jooq.tables.pojos.GithubLinks value) {
        super(GithubLinks.GITHUB_LINKS);

        if (value != null) {
            setLinkId(value.getLinkId());
            setPullRequestsCount(value.getPullRequestsCount());
            resetChangedOnNotNull();
        }
    }
}
