/*
 * This file is generated by jOOQ.
 */
package edu.java.repository.jooq.tables.records;

import edu.java.repository.jooq.tables.StackoverflowLinks;
import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StackoverflowLinksRecord extends UpdatableRecordImpl<StackoverflowLinksRecord> implements Record2<Long, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>STACKOVERFLOW_LINKS.LINK_ID</code>.
     */
    public void setLinkId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>STACKOVERFLOW_LINKS.LINK_ID</code>.
     */
    @Nullable
    public Long getLinkId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>STACKOVERFLOW_LINKS.ANSWERS_COUNT</code>.
     */
    public void setAnswersCount(@Nullable Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>STACKOVERFLOW_LINKS.ANSWERS_COUNT</code>.
     */
    @Nullable
    public Integer getAnswersCount() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Long, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return StackoverflowLinks.STACKOVERFLOW_LINKS.LINK_ID;
    }

    @Override
    @NotNull
    public Field<Integer> field2() {
        return StackoverflowLinks.STACKOVERFLOW_LINKS.ANSWERS_COUNT;
    }

    @Override
    @Nullable
    public Long component1() {
        return getLinkId();
    }

    @Override
    @Nullable
    public Integer component2() {
        return getAnswersCount();
    }

    @Override
    @Nullable
    public Long value1() {
        return getLinkId();
    }

    @Override
    @Nullable
    public Integer value2() {
        return getAnswersCount();
    }

    @Override
    @NotNull
    public StackoverflowLinksRecord value1(@Nullable Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public StackoverflowLinksRecord value2(@Nullable Integer value) {
        setAnswersCount(value);
        return this;
    }

    @Override
    @NotNull
    public StackoverflowLinksRecord values(@Nullable Long value1, @Nullable Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StackoverflowLinksRecord
     */
    public StackoverflowLinksRecord() {
        super(StackoverflowLinks.STACKOVERFLOW_LINKS);
    }

    /**
     * Create a detached, initialised StackoverflowLinksRecord
     */
    @ConstructorProperties({ "linkId", "answersCount" })
    public StackoverflowLinksRecord(@Nullable Long linkId, @Nullable Integer answersCount) {
        super(StackoverflowLinks.STACKOVERFLOW_LINKS);

        setLinkId(linkId);
        setAnswersCount(answersCount);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised StackoverflowLinksRecord
     */
    public StackoverflowLinksRecord(edu.java.repository.jooq.tables.pojos.StackoverflowLinks value) {
        super(StackoverflowLinks.STACKOVERFLOW_LINKS);

        if (value != null) {
            setLinkId(value.getLinkId());
            setAnswersCount(value.getAnswersCount());
            resetChangedOnNotNull();
        }
    }
}
