/*
 * This file is generated by jOOQ.
 */

package edu.java.repository.jooq.tables.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GithubLinks implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long linkId;
    private Integer pullRequestsCount;

    public GithubLinks() {}

    public GithubLinks(GithubLinks value) {
        this.linkId = value.linkId;
        this.pullRequestsCount = value.pullRequestsCount;
    }

    @ConstructorProperties({ "linkId", "pullRequestsCount" })
    public GithubLinks(
        @Nullable Long linkId,
        @Nullable Integer pullRequestsCount
    ) {
        this.linkId = linkId;
        this.pullRequestsCount = pullRequestsCount;
    }

    /**
     * Getter for <code>GITHUB_LINKS.LINK_ID</code>.
     */
    @Nullable
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>GITHUB_LINKS.LINK_ID</code>.
     */
    public void setLinkId(@Nullable Long linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>GITHUB_LINKS.PULL_REQUESTS_COUNT</code>.
     */
    @Nullable
    public Integer getPullRequestsCount() {
        return this.pullRequestsCount;
    }

    /**
     * Setter for <code>GITHUB_LINKS.PULL_REQUESTS_COUNT</code>.
     */
    public void setPullRequestsCount(@Nullable Integer pullRequestsCount) {
        this.pullRequestsCount = pullRequestsCount;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final GithubLinks other = (GithubLinks) obj;
        if (this.linkId == null) {
            if (other.linkId != null)
                return false;
        }
        else if (!this.linkId.equals(other.linkId))
            return false;
        if (this.pullRequestsCount == null) {
            if (other.pullRequestsCount != null)
                return false;
        }
        else if (!this.pullRequestsCount.equals(other.pullRequestsCount))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.pullRequestsCount == null) ? 0 : this.pullRequestsCount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GithubLinks (");

        sb.append(linkId);
        sb.append(", ").append(pullRequestsCount);

        sb.append(")");
        return sb.toString();
    }
}
