/*
 * This file is generated by jOOQ.
 */

package edu.java.repository.jooq.tables.pojos;

import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import java.io.Serializable;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sites implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String siteName;

    public Sites() {}

    public Sites(Sites value) {
        this.id = value.id;
        this.siteName = value.siteName;
    }

    @ConstructorProperties({ "id", "siteName" })
    public Sites(
        @Nullable Long id,
        @NotNull String siteName
    ) {
        this.id = id;
        this.siteName = siteName;
    }

    /**
     * Getter for <code>SITES.ID</code>.
     */
    @Nullable
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>SITES.ID</code>.
     */
    public void setId(@Nullable Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>SITES.SITE_NAME</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 255)
    @NotNull
    public String getSiteName() {
        return this.siteName;
    }

    /**
     * Setter for <code>SITES.SITE_NAME</code>.
     */
    public void setSiteName(@NotNull String siteName) {
        this.siteName = siteName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Sites other = (Sites) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.siteName == null) {
            if (other.siteName != null)
                return false;
        }
        else if (!this.siteName.equals(other.siteName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.siteName == null) ? 0 : this.siteName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Sites (");

        sb.append(id);
        sb.append(", ").append(siteName);

        sb.append(")");
        return sb.toString();
    }
}
