/*
 * This file is generated by jOOQ.
 */
package repository.jooq.tables.records;


import java.beans.ConstructorProperties;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import repository.jooq.tables.GithubLinks;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GithubLinksRecord extends UpdatableRecordImpl<GithubLinksRecord> implements Record3<Long, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GITHUB_LINKS.LINK_ID</code>.
     */
    public void setLinkId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>GITHUB_LINKS.LINK_ID</code>.
     */
    @Nullable
    public Long getLinkId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>GITHUB_LINKS.LAST_PUSH</code>.
     */
    public void setLastPush(@Nullable LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>GITHUB_LINKS.LAST_PUSH</code>.
     */
    @Nullable
    public LocalDateTime getLastPush() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>GITHUB_LINKS.PULL_REQUESTS_COUNT</code>.
     */
    public void setPullRequestsCount(@Nullable Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>GITHUB_LINKS.PULL_REQUESTS_COUNT</code>.
     */
    @Nullable
    public Integer getPullRequestsCount() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, LocalDateTime, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Long, LocalDateTime, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return GithubLinks.GITHUB_LINKS.LINK_ID;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field2() {
        return GithubLinks.GITHUB_LINKS.LAST_PUSH;
    }

    @Override
    @NotNull
    public Field<Integer> field3() {
        return GithubLinks.GITHUB_LINKS.PULL_REQUESTS_COUNT;
    }

    @Override
    @Nullable
    public Long component1() {
        return getLinkId();
    }

    @Override
    @Nullable
    public LocalDateTime component2() {
        return getLastPush();
    }

    @Override
    @Nullable
    public Integer component3() {
        return getPullRequestsCount();
    }

    @Override
    @Nullable
    public Long value1() {
        return getLinkId();
    }

    @Override
    @Nullable
    public LocalDateTime value2() {
        return getLastPush();
    }

    @Override
    @Nullable
    public Integer value3() {
        return getPullRequestsCount();
    }

    @Override
    @NotNull
    public GithubLinksRecord value1(@Nullable Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public GithubLinksRecord value2(@Nullable LocalDateTime value) {
        setLastPush(value);
        return this;
    }

    @Override
    @NotNull
    public GithubLinksRecord value3(@Nullable Integer value) {
        setPullRequestsCount(value);
        return this;
    }

    @Override
    @NotNull
    public GithubLinksRecord values(@Nullable Long value1, @Nullable LocalDateTime value2, @Nullable Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GithubLinksRecord
     */
    public GithubLinksRecord() {
        super(GithubLinks.GITHUB_LINKS);
    }

    /**
     * Create a detached, initialised GithubLinksRecord
     */
    @ConstructorProperties({ "linkId", "lastPush", "pullRequestsCount" })
    public GithubLinksRecord(@Nullable Long linkId, @Nullable LocalDateTime lastPush, @Nullable Integer pullRequestsCount) {
        super(GithubLinks.GITHUB_LINKS);

        setLinkId(linkId);
        setLastPush(lastPush);
        setPullRequestsCount(pullRequestsCount);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised GithubLinksRecord
     */
    public GithubLinksRecord(repository.jooq.tables.pojos.GithubLinks value) {
        super(GithubLinks.GITHUB_LINKS);

        if (value != null) {
            setLinkId(value.getLinkId());
            setLastPush(value.getLastPush());
            setPullRequestsCount(value.getPullRequestsCount());
            resetChangedOnNotNull();
        }
    }
}
