/*
 * This file is generated by jOOQ.
 */
package repository.jooq.tables.records;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import repository.jooq.tables.Sites;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SitesRecord extends UpdatableRecordImpl<SitesRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SITES.ID</code>.
     */
    public void setId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>SITES.ID</code>.
     */
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>SITES.SITE_NAME</code>.
     */
    public void setSiteName(@NotNull String value) {
        set(1, value);
    }

    /**
     * Getter for <code>SITES.SITE_NAME</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 255)
    @NotNull
    public String getSiteName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Sites.SITES.ID;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return Sites.SITES.SITE_NAME;
    }

    @Override
    @Nullable
    public Long component1() {
        return getId();
    }

    @Override
    @NotNull
    public String component2() {
        return getSiteName();
    }

    @Override
    @Nullable
    public Long value1() {
        return getId();
    }

    @Override
    @NotNull
    public String value2() {
        return getSiteName();
    }

    @Override
    @NotNull
    public SitesRecord value1(@Nullable Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public SitesRecord value2(@NotNull String value) {
        setSiteName(value);
        return this;
    }

    @Override
    @NotNull
    public SitesRecord values(@Nullable Long value1, @NotNull String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SitesRecord
     */
    public SitesRecord() {
        super(Sites.SITES);
    }

    /**
     * Create a detached, initialised SitesRecord
     */
    @ConstructorProperties({ "id", "siteName" })
    public SitesRecord(@Nullable Long id, @NotNull String siteName) {
        super(Sites.SITES);

        setId(id);
        setSiteName(siteName);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SitesRecord
     */
    public SitesRecord(repository.jooq.tables.pojos.Sites value) {
        super(Sites.SITES);

        if (value != null) {
            setId(value.getId());
            setSiteName(value.getSiteName());
            resetChangedOnNotNull();
        }
    }
}
